EAT-56326: method to check if chart exists in database
telia-oss/xjog pull request #9
Opened 2024-10-08 12:48 UTC by duttiv

If XJog has previously returned null but this check reveals the chart exists, eCom can now throw err0r

2024-10-08 12:49 UTC, duttiv commented on packages/core-pg/src/PostgresPersistenceAdapter.ts
> +  protected async chartExists(
I tried to make it similar to `isActivityRegistered` method

2024-10-09 08:03 UTC, martvalja approved these changes
A couple of questions, otherwise looking good

2024-10-09 08:03 UTC, martvalja commented on packages/core/src/XJog.ts
> +      return null;
Maybe return false instead so this only returns booleans? Or maybe even throw/reject promise 🤷‍♂️

2024-10-09 08:04 UTC, martvalja requested changes
Ah, bump versions as well for the necessary packages.

2024-10-10 17:21 UTC, duttiv commented on packages/core/src/XJog.ts
> +      return null;
Decided to just return false, as it seemed cleaner

2024-10-10 17:24 UTC, duttiv commented
> Ah, bump versions as well for the necessary packages (packages that were changed + packages that depend on those.
> 
> Guide: https://github.com/telia-oss/xjog/blob/main/contributing/development.md#versioning-and-publishing

Ouch, ignore for now because I somehow forgot to do the thing I was most anxious about. I'll update version tomorrow and then request the review again

2024-10-11 13:17 UTC, merged